"""Paso 10: resenas

Revision ID: 0dcb482e9761
Revises: a5a0f8380534
Create Date: 2026-06-01 20:45:59.424595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dcb482e9761'
down_revision = 'a5a0f8380534'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resenas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('calificacion', sa.SmallInteger(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('respuesta', sa.Text(), nullable=True),
    sa.Column('respondida_at', sa.DateTime(), nullable=True),
    sa.Column('oculta', sa.Boolean(), nullable=False),
    sa.Column('solicita_ocultar', sa.Boolean(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('calificacion >= 1 AND calificacion <= 5', name='ck_resena_calificacion'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reserva_id')
    )
    with op.batch_alter_table('resenas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resenas_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resenas_negocio_id'), ['negocio_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resenas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resenas_negocio_id'))
        batch_op.drop_index(batch_op.f('ix_resenas_cliente_id'))

    op.drop_table('resenas')
    # ### end Alembic commands ###
