"""Mensajes automaticos: toggles + firma en negocio

Revision ID: 0f86a941c8c7
Revises: 70827e47217e
Create Date: 2026-06-02 19:56:51.144469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f86a941c8c7'
down_revision = '70827e47217e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('negocios', schema=None) as batch_op:
        # Booleanos NOT NULL: server_default 'true' para poblar filas existentes.
        batch_op.add_column(sa.Column('notif_confirmacion', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('notif_recordatorio', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('notif_canal_email', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('notif_canal_whatsapp', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('mensaje_firma', sa.String(length=280), nullable=True))

    # Quitar los server_default (el default lo aporta el modelo).
    with op.batch_alter_table('negocios', schema=None) as batch_op:
        for col in ('notif_confirmacion', 'notif_recordatorio', 'notif_canal_email', 'notif_canal_whatsapp'):
            batch_op.alter_column(col, server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('negocios', schema=None) as batch_op:
        batch_op.drop_column('mensaje_firma')
        batch_op.drop_column('notif_canal_whatsapp')
        batch_op.drop_column('notif_canal_email')
        batch_op.drop_column('notif_recordatorio')
        batch_op.drop_column('notif_confirmacion')

    # ### end Alembic commands ###
