"""Paso 7: clientes y reservas

Revision ID: 10ab154ab0a3
Revises: 87443a05605f
Create Date: 2026-06-01 20:26:50.448173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10ab154ab0a3'
down_revision = '87443a05605f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=40), nullable=True),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('negocio_id', 'email', name='uq_cliente_negocio_email')
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clientes_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_clientes_negocio_id'), ['negocio_id'], unique=False)

    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=12), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('recurso_id', sa.Integer(), nullable=False),
    sa.Column('inicio', sa.DateTime(), nullable=False),
    sa.Column('fin', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE_PAGO', 'CONFIRMADO', 'EN_PROCESO', 'FINALIZADO', 'CANCELADO', 'AUSENTE', 'REPROGRAMADO', name='estadoreservaenum', native_enum=False, length=20), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('fin > inicio', name='ck_reserva_rango'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recurso_id'], ['recursos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.create_index('ix_reserva_negocio_inicio', ['negocio_id', 'inicio'], unique=False)
        batch_op.create_index('ix_reserva_recurso_inicio', ['recurso_id', 'inicio'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservas_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservas_codigo'), ['codigo'], unique=True)
        batch_op.create_index(batch_op.f('ix_reservas_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservas_negocio_id'), ['negocio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservas_recurso_id'), ['recurso_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservas_servicio_id'), ['servicio_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservas_servicio_id'))
        batch_op.drop_index(batch_op.f('ix_reservas_recurso_id'))
        batch_op.drop_index(batch_op.f('ix_reservas_negocio_id'))
        batch_op.drop_index(batch_op.f('ix_reservas_estado'))
        batch_op.drop_index(batch_op.f('ix_reservas_codigo'))
        batch_op.drop_index(batch_op.f('ix_reservas_cliente_id'))
        batch_op.drop_index('ix_reserva_recurso_inicio')
        batch_op.drop_index('ix_reserva_negocio_inicio')

    op.drop_table('reservas')
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_negocio_id'))
        batch_op.drop_index(batch_op.f('ix_clientes_email'))

    op.drop_table('clientes')
    # ### end Alembic commands ###
