"""profesional: tipografia, estilo_pagina, forma_foto

Revision ID: 17cc05ecd125
Revises: c3408e31c9b3
Create Date: 2026-06-04 04:00:10.444335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17cc05ecd125'
down_revision = 'c3408e31c9b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # NOT NULL con default temporal para no romper filas existentes.
    with op.batch_alter_table('recursos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipografia', sa.String(length=60),
                                      nullable=False, server_default='Plus Jakarta Sans'))
        batch_op.add_column(sa.Column('estilo_pagina', sa.String(length=20),
                                      nullable=False, server_default='minimal'))
        batch_op.add_column(sa.Column('forma_foto', sa.String(length=20),
                                      nullable=False, server_default='circulo'))

    # Quitamos los defaults temporales: la app siempre setea el valor.
    with op.batch_alter_table('recursos', schema=None) as batch_op:
        batch_op.alter_column('tipografia', server_default=None)
        batch_op.alter_column('estilo_pagina', server_default=None)
        batch_op.alter_column('forma_foto', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recursos', schema=None) as batch_op:
        batch_op.drop_column('forma_foto')
        batch_op.drop_column('estilo_pagina')
        batch_op.drop_column('tipografia')

    # ### end Alembic commands ###
