"""Paso 5: servicios + servicio_recurso

Revision ID: 19d24edaca9c
Revises: 9882df3c7ce3
Create Date: 2026-06-01 20:08:46.758285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19d24edaca9c'
down_revision = '9882df3c7ce3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('duracion_minutos', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('duracion_minutos >= 1', name='ck_servicio_duracion_min'),
    sa.CheckConstraint('precio >= 0', name='ck_servicio_precio_no_negativo'),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('negocio_id', 'slug', name='uq_servicio_negocio_slug')
    )
    with op.batch_alter_table('servicios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_servicios_negocio_id'), ['negocio_id'], unique=False)

    op.create_table('servicio_recurso',
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('recurso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recurso_id'], ['recursos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('servicio_id', 'recurso_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servicio_recurso')
    with op.batch_alter_table('servicios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_servicios_negocio_id'))

    op.drop_table('servicios')
    # ### end Alembic commands ###
