"""negocio: descuento_plan + cortesia (super admin)

Revision ID: 21101ef64ea0
Revises: 8d0c92b95c84
Create Date: 2026-06-06 16:46:15.965099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21101ef64ea0'
down_revision = '8d0c92b95c84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('negocios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descuento_plan', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cortesia', sa.Boolean(), nullable=False,
                                      server_default=sa.false()))
    with op.batch_alter_table('negocios', schema=None) as batch_op:
        batch_op.alter_column('cortesia', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('negocios', schema=None) as batch_op:
        batch_op.drop_column('cortesia')
        batch_op.drop_column('descuento_plan')

    # ### end Alembic commands ###
