"""reserva.recordatorio_2h_enviado

Revision ID: 21aed3c2d41b
Revises: a3d1bac26527
Create Date: 2026-06-06 15:54:42.150878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21aed3c2d41b'
down_revision = 'a3d1bac26527'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recordatorio_2h_enviado', sa.Boolean(),
                                      nullable=False, server_default=sa.false()))
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.alter_column('recordatorio_2h_enviado', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.drop_column('recordatorio_2h_enviado')

    # ### end Alembic commands ###
