"""Galeria de fotos

Revision ID: 2a60367f5b31
Revises: 0f86a941c8c7
Create Date: 2026-06-02 20:05:11.767034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a60367f5b31'
down_revision = '0f86a941c8c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('galeria_fotos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('galeria_fotos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_galeria_fotos_negocio_id'), ['negocio_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('galeria_fotos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_galeria_fotos_negocio_id'))

    op.drop_table('galeria_fotos')
    # ### end Alembic commands ###
