"""negocio direccion+mp_token, recurso avatar_posicion

Revision ID: 4206492e0d1b
Revises: 4312ed901c82
Create Date: 2026-06-04 20:28:45.504772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4206492e0d1b'
down_revision = '4312ed901c82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('negocios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('mercadopago_token', sa.String(length=255), nullable=True))

    with op.batch_alter_table('recursos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_posicion', sa.String(length=12), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recursos', schema=None) as batch_op:
        batch_op.drop_column('avatar_posicion')

    with op.batch_alter_table('negocios', schema=None) as batch_op:
        batch_op.drop_column('mercadopago_token')
        batch_op.drop_column('direccion')

    # ### end Alembic commands ###
