"""pagos: suscripcion (reserva opcional, concepto, plan_destino)

Revision ID: 4312ed901c82
Revises: 8d6824f81901
Create Date: 2026-06-04 15:42:48.026033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4312ed901c82'
down_revision = '8d6824f81901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('concepto', sa.String(length=20),
                                      nullable=False, server_default='sena'))
        batch_op.add_column(sa.Column('plan_destino', sa.String(length=20), nullable=True))
        batch_op.alter_column('reserva_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.alter_column('concepto', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.alter_column('reserva_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('plan_destino')
        batch_op.drop_column('concepto')

    # ### end Alembic commands ###
