"""reserva asistencia_confirmada + politica de cancelacion/reembolso

Revision ID: 51073eba9be0
Revises: 54dc821c4ea3
Create Date: 2026-06-05 04:02:00.703439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51073eba9be0'
down_revision = '54dc821c4ea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('negocios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancelacion_horas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reembolso_sena_horas', sa.Integer(), nullable=True))

    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asistencia_confirmada', sa.Boolean(),
                                      nullable=False, server_default=sa.false()))
    # Quitar el default temporal: la app provee el valor en adelante.
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.alter_column('asistencia_confirmada', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.drop_column('asistencia_confirmada')

    with op.batch_alter_table('negocios', schema=None) as batch_op:
        batch_op.drop_column('reembolso_sena_horas')
        batch_op.drop_column('cancelacion_horas')

    # ### end Alembic commands ###
