"""sena porcentaje + alias de transferencia del negocio

Revision ID: 54dc821c4ea3
Revises: 1e6b5f04e93d
Create Date: 2026-06-05 00:36:39.751013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54dc821c4ea3'
down_revision = '1e6b5f04e93d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('negocios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alias_transferencia', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('titular_transferencia', sa.String(length=120), nullable=True))

    with op.batch_alter_table('servicios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sena_porcentaje', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicios', schema=None) as batch_op:
        batch_op.drop_column('sena_porcentaje')

    with op.batch_alter_table('negocios', schema=None) as batch_op:
        batch_op.drop_column('titular_transferencia')
        batch_op.drop_column('alias_transferencia')

    # ### end Alembic commands ###
