"""Paso 2: negocios, roles, usuarios

Revision ID: 603cdf8794f2
Revises: 
Create Date: 2026-06-01 19:45:27.336809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '603cdf8794f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('negocios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('rubro', sa.Enum('MANICURA', 'PELUQUERIA', 'BARBERIA', 'LASHISTA', 'ESTETICA', 'SPA', 'PSICOLOGIA', 'NUTRICION', 'CONSULTORIO', 'CANCHA_FUTBOL', 'CANCHA_PADEL', 'TENIS', 'COWORKING', 'SALA_REUNIONES', 'OTRO', name='rubroenum', native_enum=False, length=30), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=40), nullable=True),
    sa.Column('ciudad', sa.String(length=80), nullable=True),
    sa.Column('visible_marketplace', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('plan', sa.Enum('BASICO', 'PRO', 'PREMIUM', 'STARTER', 'BUSINESS', 'ENTERPRISE', name='planenum', native_enum=False, length=20), nullable=True),
    sa.Column('estado_suscripcion', sa.Enum('TRIAL', 'ACTIVA', 'VENCIDA', 'CANCELADA', name='estadosuscripcionenum', native_enum=False, length=20), nullable=False),
    sa.Column('trial_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suscripcion_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('negocios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_negocios_ciudad'), ['ciudad'], unique=False)
        batch_op.create_index(batch_op.f('ix_negocios_slug'), ['slug'], unique=True)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=40), nullable=False),
    sa.Column('descripcion', sa.String(length=160), nullable=True),
    sa.Column('es_sistema', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_nombre'), ['nombre'], unique=True)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=True),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellido', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_negocio_id'), ['negocio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuarios_rol_id'), ['rol_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_rol_id'))
        batch_op.drop_index(batch_op.f('ix_usuarios_negocio_id'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_nombre'))

    op.drop_table('roles')
    with op.batch_alter_table('negocios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_negocios_slug'))
        batch_op.drop_index(batch_op.f('ix_negocios_ciudad'))

    op.drop_table('negocios')
    # ### end Alembic commands ###
