"""negocio: campos OAuth de Mercado Pago (Connect)

Revision ID: 6dc751241493
Revises: 4206492e0d1b
Create Date: 2026-06-04 20:53:15.099698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dc751241493'
down_revision = '4206492e0d1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('negocios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mp_refresh_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('mp_user_id', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('mp_public_key', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('mp_token_expira', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('negocios', schema=None) as batch_op:
        batch_op.drop_column('mp_token_expira')
        batch_op.drop_column('mp_public_key')
        batch_op.drop_column('mp_user_id')
        batch_op.drop_column('mp_refresh_token')

    # ### end Alembic commands ###
