"""Paso 20: metodo_pago en negocio

Revision ID: 70827e47217e
Revises: f0a0ab663351
Create Date: 2026-06-02 16:03:18.937629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70827e47217e'
down_revision = 'f0a0ab663351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('negocios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metodo_pago', sa.Enum('MERCADOPAGO', 'NARANJA_X', 'MODO', name='metodopagoenum', native_enum=False, length=20), nullable=False, server_default='MERCADOPAGO'))

    # Quitar el server_default (el valor por defecto lo aporta el modelo).
    with op.batch_alter_table('negocios', schema=None) as batch_op:
        batch_op.alter_column('metodo_pago', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('negocios', schema=None) as batch_op:
        batch_op.drop_column('metodo_pago')

    # ### end Alembic commands ###
