"""Paso 6: horarios_atencion y bloqueos

Revision ID: 87443a05605f
Revises: 19d24edaca9c
Create Date: 2026-06-01 20:17:32.297077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87443a05605f'
down_revision = '19d24edaca9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bloqueos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recurso_id', sa.Integer(), nullable=True),
    sa.Column('inicio', sa.DateTime(), nullable=False),
    sa.Column('fin', sa.DateTime(), nullable=False),
    sa.Column('motivo', sa.String(length=160), nullable=True),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('fin > inicio', name='ck_bloqueo_rango'),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recurso_id'], ['recursos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bloqueos', schema=None) as batch_op:
        batch_op.create_index('ix_bloqueo_negocio_inicio', ['negocio_id', 'inicio'], unique=False)
        batch_op.create_index(batch_op.f('ix_bloqueos_negocio_id'), ['negocio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bloqueos_recurso_id'), ['recurso_id'], unique=False)

    op.create_table('horarios_atencion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recurso_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.SmallInteger(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('dia_semana >= 0 AND dia_semana <= 6', name='ck_horario_dia'),
    sa.CheckConstraint('hora_fin > hora_inicio', name='ck_horario_rango'),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recurso_id'], ['recursos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('horarios_atencion', schema=None) as batch_op:
        batch_op.create_index('ix_horario_recurso_dia', ['recurso_id', 'dia_semana'], unique=False)
        batch_op.create_index(batch_op.f('ix_horarios_atencion_negocio_id'), ['negocio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_horarios_atencion_recurso_id'), ['recurso_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horarios_atencion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_horarios_atencion_recurso_id'))
        batch_op.drop_index(batch_op.f('ix_horarios_atencion_negocio_id'))
        batch_op.drop_index('ix_horario_recurso_dia')

    op.drop_table('horarios_atencion')
    with op.batch_alter_table('bloqueos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bloqueos_recurso_id'))
        batch_op.drop_index(batch_op.f('ix_bloqueos_negocio_id'))
        batch_op.drop_index('ix_bloqueo_negocio_inicio')

    op.drop_table('bloqueos')
    # ### end Alembic commands ###
