"""cupones (gift cards) + reserva.cupon_codigo

Revision ID: 8d0c92b95c84
Revises: 21aed3c2d41b
Create Date: 2026-06-06 16:42:16.986272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d0c92b95c84'
down_revision = '21aed3c2d41b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cupones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=24), nullable=False),
    sa.Column('descripcion', sa.String(length=120), nullable=True),
    sa.Column('tipo', sa.String(length=12), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('vence', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usos_max', sa.Integer(), nullable=True),
    sa.Column('usos', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('negocio_id', 'codigo', name='uq_cupon_negocio_codigo')
    )
    with op.batch_alter_table('cupones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cupones_codigo'), ['codigo'], unique=False)
        batch_op.create_index(batch_op.f('ix_cupones_negocio_id'), ['negocio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cupones_servicio_id'), ['servicio_id'], unique=False)

    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cupon_codigo', sa.String(length=24), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.drop_column('cupon_codigo')

    with op.batch_alter_table('cupones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cupones_servicio_id'))
        batch_op.drop_index(batch_op.f('ix_cupones_negocio_id'))
        batch_op.drop_index(batch_op.f('ix_cupones_codigo'))

    op.drop_table('cupones')
    # ### end Alembic commands ###
