"""reserva: resena_pedida

Revision ID: 8d6824f81901
Revises: f2e54e814217
Create Date: 2026-06-04 15:32:33.984728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d6824f81901'
down_revision = 'f2e54e814217'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resena_pedida', sa.Boolean(),
                                      nullable=False, server_default=sa.false()))
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.alter_column('resena_pedida', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.drop_column('resena_pedida')

    # ### end Alembic commands ###
