"""Paso 4: tipos_recurso y recursos

Revision ID: 9882df3c7ce3
Revises: 603cdf8794f2
Create Date: 2026-06-01 19:57:43.870974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9882df3c7ce3'
down_revision = '603cdf8794f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_recurso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('negocio_id', 'slug', name='uq_tiporecurso_negocio_slug')
    )
    with op.batch_alter_table('tipos_recurso', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tipos_recurso_negocio_id'), ['negocio_id'], unique=False)

    op.create_table('recursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_recurso_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('capacidad', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('capacidad >= 1', name='ck_recurso_capacidad_min'),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tipo_recurso_id'], ['tipos_recurso.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('negocio_id', 'slug', name='uq_recurso_negocio_slug')
    )
    with op.batch_alter_table('recursos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recursos_negocio_id'), ['negocio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recursos_tipo_recurso_id'), ['tipo_recurso_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recursos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recursos_tipo_recurso_id'))
        batch_op.drop_index(batch_op.f('ix_recursos_negocio_id'))

    op.drop_table('recursos')
    with op.batch_alter_table('tipos_recurso', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tipos_recurso_negocio_id'))

    op.drop_table('tipos_recurso')
    # ### end Alembic commands ###
