"""quitar metodo_pago (solo mercadopago)

Revision ID: 9c4fdf66f86b
Revises: 17cc05ecd125
Create Date: 2026-06-04 14:09:00.286738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c4fdf66f86b'
down_revision = '17cc05ecd125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('negocios', schema=None) as batch_op:
        batch_op.drop_column('metodo_pago')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('negocios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metodo_pago', sa.VARCHAR(length=20),
                                      autoincrement=False, nullable=False,
                                      server_default='mercadopago'))

    # ### end Alembic commands ###
