"""Creditos de WhatsApp: wa_extra/usados/periodo

Revision ID: a356e46054df
Revises: e6fd41abfafd
Create Date: 2026-06-03 04:07:51.511052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a356e46054df'
down_revision = 'e6fd41abfafd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('negocios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wa_extra', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('wa_usados', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('wa_periodo', sa.String(length=7), nullable=True))

    with op.batch_alter_table('negocios', schema=None) as batch_op:
        batch_op.alter_column('wa_extra', server_default=None)
        batch_op.alter_column('wa_usados', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('negocios', schema=None) as batch_op:
        batch_op.drop_column('wa_periodo')
        batch_op.drop_column('wa_usados')
        batch_op.drop_column('wa_extra')

    # ### end Alembic commands ###
