"""negocio.wa_extra_vence (packs WhatsApp por 30 dias)

Revision ID: a3d1bac26527
Revises: e126d2da75f1
Create Date: 2026-06-06 14:18:17.909286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3d1bac26527'
down_revision = 'e126d2da75f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('negocios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wa_extra_vence', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('negocios', schema=None) as batch_op:
        batch_op.drop_column('wa_extra_vence')

    # ### end Alembic commands ###
