"""Paso 8: pagos + sena en servicios

Revision ID: a5a0f8380534
Revises: 10ab154ab0a3
Create Date: 2026-06-01 20:37:24.508041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5a0f8380534'
down_revision = '10ab154ab0a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'APROBADO', 'RECHAZADO', 'REEMBOLSADO', name='pagoestadoenum', native_enum=False, length=20), nullable=False),
    sa.Column('proveedor', sa.Enum('MERCADOPAGO', 'NARANJA_X', 'MODO', 'SIMULADO', 'MANUAL', name='proveedorpagoenum', native_enum=False, length=20), nullable=False),
    sa.Column('es_sena', sa.Boolean(), nullable=False),
    sa.Column('preference_id', sa.String(length=120), nullable=True),
    sa.Column('external_id', sa.String(length=120), nullable=True),
    sa.Column('init_point', sa.String(length=500), nullable=True),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pagos_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_pagos_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pagos_negocio_id'), ['negocio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pagos_reserva_id'), ['reserva_id'], unique=False)

    with op.batch_alter_table('servicios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requiere_sena', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('sena_monto', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicios', schema=None) as batch_op:
        batch_op.drop_column('sena_monto')
        batch_op.drop_column('requiere_sena')

    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagos_reserva_id'))
        batch_op.drop_index(batch_op.f('ix_pagos_negocio_id'))
        batch_op.drop_index(batch_op.f('ix_pagos_external_id'))
        batch_op.drop_index(batch_op.f('ix_pagos_estado'))

    op.drop_table('pagos')
    # ### end Alembic commands ###
