"""Profesional: foto y especialidad

Revision ID: bc0f72e2c42b
Revises: a356e46054df
Create Date: 2026-06-03 18:36:07.061214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc0f72e2c42b'
down_revision = 'a356e46054df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recursos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_filename', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('especialidad', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recursos', schema=None) as batch_op:
        batch_op.drop_column('especialidad')
        batch_op.drop_column('foto_filename')

    # ### end Alembic commands ###
