"""personalizacion profesional: banner, frase, color, habilidades, redes

Revision ID: c3408e31c9b3
Revises: bc0f72e2c42b
Create Date: 2026-06-03 19:18:54.517581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3408e31c9b3'
down_revision = 'bc0f72e2c42b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recursos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banner_filename', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('frase', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('color_acento', sa.String(length=7), nullable=True))
        # NOT NULL con default temporal para no romper filas existentes.
        batch_op.add_column(sa.Column('estilo_cabecera', sa.String(length=20),
                                      nullable=False, server_default='degradado'))
        batch_op.add_column(sa.Column('anios_experiencia', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('habilidades', sa.String(length=400), nullable=True))
        batch_op.add_column(sa.Column('instagram', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('whatsapp', sa.String(length=40), nullable=True))

    # Quitamos el default temporal: la app siempre setea el valor explícito.
    with op.batch_alter_table('recursos', schema=None) as batch_op:
        batch_op.alter_column('estilo_cabecera', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recursos', schema=None) as batch_op:
        batch_op.drop_column('whatsapp')
        batch_op.drop_column('instagram')
        batch_op.drop_column('habilidades')
        batch_op.drop_column('anios_experiencia')
        batch_op.drop_column('estilo_cabecera')
        batch_op.drop_column('color_acento')
        batch_op.drop_column('frase')
        batch_op.drop_column('banner_filename')

    # ### end Alembic commands ###
