"""centro de notificaciones in-app (campanita)

Revision ID: e126d2da75f1
Revises: 51073eba9be0
Create Date: 2026-06-05 13:20:23.258150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e126d2da75f1'
down_revision = '51073eba9be0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('titulo', sa.String(length=160), nullable=False),
    sa.Column('mensaje', sa.String(length=400), nullable=True),
    sa.Column('url', sa.String(length=300), nullable=True),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notificaciones_leida'), ['leida'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificaciones_negocio_id'), ['negocio_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notificaciones_negocio_id'))
        batch_op.drop_index(batch_op.f('ix_notificaciones_leida'))

    op.drop_table('notificaciones')
    # ### end Alembic commands ###
