"""Horarios alternados: columna semana A/B

Revision ID: e6fd41abfafd
Revises: 2a60367f5b31
Create Date: 2026-06-02 20:07:34.397269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6fd41abfafd'
down_revision = '2a60367f5b31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horarios_atencion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semana', sa.Enum('TODAS', 'A', 'B', name='semanaenum', native_enum=False, length=10), nullable=False, server_default='TODAS'))

    with op.batch_alter_table('horarios_atencion', schema=None) as batch_op:
        batch_op.alter_column('semana', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horarios_atencion', schema=None) as batch_op:
        batch_op.drop_column('semana')

    # ### end Alembic commands ###
