"""Paso 12: personalizacion del negocio

Revision ID: f0a0ab663351
Revises: 0dcb482e9761
Create Date: 2026-06-02 04:00:31.761485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0a0ab663351'
down_revision = '0dcb482e9761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('negocios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_filename', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('banner_filename', sa.String(length=200), nullable=True))
        # Columnas NOT NULL: usamos server_default para poblar filas existentes;
        # luego lo quitamos para que el default lo maneje la app (modelo).
        batch_op.add_column(sa.Column('color_primario', sa.String(length=7), nullable=False, server_default='#0d6efd'))
        batch_op.add_column(sa.Column('color_secundario', sa.String(length=7), nullable=False, server_default='#111827'))
        batch_op.add_column(sa.Column('tipografia', sa.String(length=60), nullable=False, server_default='Inter'))
        batch_op.add_column(sa.Column('template_publico', sa.Enum('MINIMAL', 'ELEGANTE', 'MODERNO', 'PREMIUM', name='templatepublicoenum', native_enum=False, length=20), nullable=False, server_default='MINIMAL'))

    # Quitar los server_default (el valor por defecto lo aporta el modelo).
    with op.batch_alter_table('negocios', schema=None) as batch_op:
        batch_op.alter_column('color_primario', server_default=None)
        batch_op.alter_column('color_secundario', server_default=None)
        batch_op.alter_column('tipografia', server_default=None)
        batch_op.alter_column('template_publico', server_default=None)
        batch_op.add_column(sa.Column('descripcion_publica', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('instagram', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('facebook', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('whatsapp', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('negocios', schema=None) as batch_op:
        batch_op.drop_column('whatsapp')
        batch_op.drop_column('facebook')
        batch_op.drop_column('instagram')
        batch_op.drop_column('descripcion_publica')
        batch_op.drop_column('template_publico')
        batch_op.drop_column('tipografia')
        batch_op.drop_column('color_secundario')
        batch_op.drop_column('color_primario')
        batch_op.drop_column('banner_filename')
        batch_op.drop_column('logo_filename')

    # ### end Alembic commands ###
