"""page-builder profesional: fondo, botones, colores, cabecera, redes

Revision ID: f2e54e814217
Revises: 9c4fdf66f86b
Create Date: 2026-06-04 14:30:33.863538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e54e814217'
down_revision = '9c4fdf66f86b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recursos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tiktok', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('pinterest', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('facebook', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('fondo_tipo', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('fondo_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('fondo_color2', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('fondo_patron', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('boton_estilo', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('boton_forma', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('color_boton', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('color_boton_texto', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('color_titulos', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('avatar_tamano', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('mostrar_portada', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('portada_efecto', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recursos', schema=None) as batch_op:
        batch_op.drop_column('portada_efecto')
        batch_op.drop_column('mostrar_portada')
        batch_op.drop_column('avatar_tamano')
        batch_op.drop_column('color_titulos')
        batch_op.drop_column('color_boton_texto')
        batch_op.drop_column('color_boton')
        batch_op.drop_column('boton_forma')
        batch_op.drop_column('boton_estilo')
        batch_op.drop_column('fondo_patron')
        batch_op.drop_column('fondo_color2')
        batch_op.drop_column('fondo_color')
        batch_op.drop_column('fondo_tipo')
        batch_op.drop_column('facebook')
        batch_op.drop_column('pinterest')
        batch_op.drop_column('tiktok')

    # ### end Alembic commands ###
